# Generated by Django 6.0.6 on 2026-06-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completo', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
