# Generated by Django 6.0.6 on 2026-06-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamodel',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefamodel',
            name='nome',
            field=models.TextField(default=''),
        ),
    ]
