# Generated by Django 6.0.6 on 2026-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefamodel_descricao_tarefamodel_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefamodel',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
